# This file originates from the work of Mateusz Pusz (https://github.com/mpusz/opt) where is licensed under MIT License.

version: 1.0.{build}

branches:
  except:
    - gh-pages

skip_commits:
  message: /\[ci skip\]/

image: Visual Studio 2017

platform:
  - x64
 
configuration:
  - Release
  - Debug

init:
  - git config --global core.autocrlf input

clone_depth: 5

install:
  - git submodule update --init --recursive

before_build:
  - mkdir build && cd build
  - cmake -G"Visual Studio 15 2017 Win64" ..

build:
  parallel: true
  project: $(APPVEYOR_BUILD_FOLDER)\build\$(APPVEYOR_PROJECT_NAME).sln

test_script:
  - '%APPVEYOR_BUILD_FOLDER%\build\src\tests\%CONFIGURATION%\stringbuilder.test.exe --gtest_output=xml:stringbuilder.test.xml'
  - if [[ "%CONFIGURATION%" == "Release" ]]; then
      '%APPVEYOR_BUILD_FOLDER%\build\src\tests\%CONFIGURATION%\stringbuilder.benchmark.exe
    fi

on_finish:
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\stringbuilder.test.xml))
